language: ruby
cache: bundler

rvm:
  - 2.6

notifications:
    email: false

before_install: gem update --system
install: bash scripts/bootstrap.sh
script: bash scripts/cibuild.sh

git:
  depth: false

env:
  matrix:
    - JEKYLL_VERSION=">= 4.0.0"
  global:
    secure: l6RDWuVqVJGvlNehtctXrI5KVuGWHZlUdv2kmC0t8Br7E1/vRCJZPfODjCwpyUtZp7lhuqs9xMNm4JqY99B0AFUy8O+xui9+tDiybVYiMX8MoO/5S7czfLyUvOnGEWPdnoslWwdB7evQmV7w2ZMLYCC5GhTk9HdYGlbynQ2aeZhD5LJKDZayj9BQgqdMcUy9FAutJBJDgUVn4ReqvpEZUJr9PAF3eCLsoYMYMgRB1tByQgC+EXdICv9JHmGC/S7HNUCk7moMOiFlna4Y75Wc1yCBfdTNjlcWy6zwjA+vsLcteRQPIIOHmtAR0kIaxc69iaE8fNIMhhbKLg96Sqr0U+kFeVl4w1eyNomvwgfpA3x03rhUDdG6eede7t9WtcH3YCbj4fg2xkKX5lOE+d47cU3K3dhU8ypfa32BXnNCY/23H6r0E8qo1Ltbus3q98nIGEjcE+tn5ViL5hpuMmiYGngh4QoJsOH//v7cgSmHWgPLpyot0cd4MEhcRr7YCxJMwJdcq1Zcn8nPkC4AVDP/KCrDj6o1mmDCvKFr6Xo7LT6fbEs6+nP7KzqghcJ512E5Rjv706cdfhHC7duSd6bI0NxTiR6fis/hO9YFZDYYR9kIXOrWEkJ61HjY8j2vPsdyRY6AfB/HuSGtKy3d0NJ/l0fwCbh8JMjNG5kvOyUVVzA=
branches:
  only:
  - master