language: ruby
cache: bundler

rvm:
  - 2.6

notifications:
    email: false

before_install: gem update --system
install: bash scripts/bootstrap.sh
script: bash scripts/cibuild.sh

git:
  depth: false

env:
  matrix:
    - JEKYLL_VERSION=">= 4.0.0"
  global:
    secure: "uOVSzzWVifmr2Z2lJwopViNinbX5VvFH3WmxEG/Eyc1cmNrTlA/0T7UilKBJIERWisifb+CB4j63BgiCj7FqJeDUCBjFnlGP55e0Fr1i/xe+2DADb4l/GeL4V96vNc8SGXNnUOJLTqm/bcmn+hRlVSSZrkWKskp6QsAIbAdaDB4uiGFZG5X0e6Cc7dgBc12l/LuVL0dS/Rn8PsEWgL+Hd3NR0wjZosHlJFGbYW95vCqLmY6BrLh1AkwkWjG7o9kZ6PwIDaiYaxpLwkV8rkmVsSiDeIxSIjQ//IDg1+QjcTHpPjXMqyCV1cV+DL19dHtB4NHMvswfppPryE8e4rlo1slU9X/f7EzjOa0Vcd0BNgzzL+quNv9d7iYDrudGC7D9VfkQcfgyQmCWXiMl8DXieFPSCZbwhUQ8Url/y/Luch3e5lgLfQZDCtfmvG1bJgiMHkL03aPJPtsLSn6FlWp7VHoIBGc2RApC/8DHiLJ72ZvJWZJWscSZiORgcWHNc4TGKW+H91wrZz5bnSMZ4qNwEq9CpPqu2wm2e6msHdXwdvtXqKpbZa0J/gPsY5NBTUvAVjQcYiepAl9fNTswqTByNOEkAISYpN4khprVlc7W5sny6vc2U91WSUeTx9C2ijrPqxEg5nJK3vdaxuHzKLjYYhOMaLPSUmX5aT1lSRST+gc="
branches:
  only:
  - master