language: ruby
cache: bundler

rvm:
  - 2.6

notifications:
    email: false

before_install: gem update --system
install: bash scripts/bootstrap.sh
script: bash scripts/cibuild.sh

git:
  depth: false

env:
  matrix:
    - JEKYLL_VERSION=">= 4.0.0"
  global:
    secure: "alQ0S0SeAifyea1lFBR0xp5k9C8WXraAko7g64K1f9vbfsG0R0cxoeL+68yHkdMLltRzODRStbhbKykAXL1Fz7kB26NbbFcRuNlmv0DRiy7t5OReD8nLRqoJ1emqdOjwqA7acWnCuz1JJSJotepOEGH6C7OOpUmxo2md2NGZOsY5FZDztdx9aG/jFRP8Dya84QY1PI/s6py5KzHxKdVg5JWJHoC5MDDaun4DdRxH922Ue9FKhHpMbBH0fuxebyeZRWU/7vpFex9badsTqNIPm2/rCSLsZP0wNm3+AdxowdjKXSFGF3m42rzAh+K4+3XxHGoG9S4G4Ot3i7at2HALKig94uc3e1A/B0UF/OKAUNVk4P3FTXHTG20yMGQCebJua7p8qfCM4qT6nx2deZ2MX/LrLE4twn+MMO6TV+znOgBRomTKFTm7WKWAYdCphoMMdSoqVYlFNapVjwJkh4su4Mmeg95DOQl4AmgocifTYnGUlMrweZcKkszdXuL8Ip3hTvOg1vLW+yOcwvaWIEzjLAPqM4cG4BRgmDRQjp3kgSV7jnhZZXLwM8X7URaY1/WStH//uCxcfuTKWPfLVR6sScyxTXbfgJA0FnvTEOzJdJ4r/86YlhE2Rt2Gd49S2coHafLkS1w4yQfHSOJRLOavN9Sxx1S/lQqirHAYfJsgAgo="    
branches:
  only:
  - master